In [26]:
import numpy as np

In [27]:
a = np.array([1,2,3,4,5])
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [28]:
b = np.array([[1],[2],[3],[4],[5]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [29]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [30]:
# Create custom arrays of zeros and ones
a = np.zeros((3,3))
print(a)

b = np.ones((3,3))
print(b)

#Array of some constants
c = np.full((3,2),5)
print(c)

#Identity Matrix - Size/Square matrix
d = np.eye(4)
print(d)

#Random Matrix
randomMatrix = np.random.random((3,2))
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.31001628 0.2902882 ]
 [0.86223959 0.84315741]
 [0.42841343 0.33630958]]


In [31]:
print(randomMatrix[ : ,1]); #slicing

[0.2902882  0.84315741 0.33630958]


In [32]:
randomMatrix[1,1:] = 1
print(randomMatrix)

[[0.31001628 0.2902882 ]
 [0.86223959 1.        ]
 [0.42841343 0.33630958]]


In [33]:
## Set some rows and columns with any values
z = np.zeros((3,3),dtype = np.int64)
print(z)
z[1,:] = 5
z[:,-1] = 7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [34]:
# Datatypes
print(z.dtype)

int64


In [35]:
# Mathematical Operations

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Element Wise Addition
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [36]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [37]:
# Matrix Multiplication / Dot Product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [38]:
# Multiplication of vector
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

print(a.dot(b))

30


In [39]:
print(sum(a))

10


In [40]:
print(np.sum(a))
print(np.sum(x,axis = 0))

10
[4 6]


In [41]:
 # Stacking of arrays
print(a)
b = b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [42]:
a = np.stack((a,b),axis = 0)

In [43]:
# Reshape a numpy array
print(a)
a = a.reshape((4,2))
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


# Numpy Random module
- rand : Random values in a given shape.
- randn : Return a sample(or samples) from the 'standard normal' distribution
- randint : Return random integers from low(inclusive) to high(exclusive)
- random : Return random floats in the half-open interval[0.0,1.0)
- choice : Genrates a random sample from a given 1-D array
- Shuffle : Shuffles the contents of a sequence

In [45]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [48]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[0 6 1 5 2 9 3 7 8 4]


In [58]:
a = np.random.randn(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

element = np.random.choice([1,4,3,2,11,27])
print(element)

[[-1.93580965  0.49249733  0.51672221]
 [ 1.15695872 -0.0350743   0.32045097]]
[5 9 7]
3


# Some more Numpy Functions - Statistics
- min,max
- mean
- median
- average
- variance
- standard variation

In [61]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
# Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

# mean, average all the elements

b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]
3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [65]:
c = np.array([1,5,4,2,0])
print(np.median(c))

# mean vs average is weighted
print(np.mean(c))

#Weights
w = np.array([1,2,3,4,5])
print(np.average(c,weights = w))



2.0
2.4
2.066666666666667


#### Standard Deviation  $$ \sigma = \sqrt{\frac{\sum\limits_{i=1}^{N}(x - \mu)^2}{N}}$$
#### Variation  $$\sigma^2$$

In [69]:
u = np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

# Inbuilt function
print(np.std(c))

#Variance
print(mystd**2)
print(np.var(c))

1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004
